name: MinIO Deployment

on:
  push:
    branches:
      - mdmn-cluster
  workflow_dispatch:
    inputs:
      destroy:
        description: 'Destroy project'
        required: true
        default: true
        type: boolean    

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' || github.event.inputs.destroy == 'false' }}
    steps:
      - name: Say Apply
        run: echo "DESTROY == false"
  destroy:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' || github.event.inputs.destroy == 'false' }}
    steps:
      - name: Say Apply
        run: echo "DESTROY == true"