name: MinIO Deployment

on:
  push:
    branches:
      - mdmn-cluster
  workflow_dispatch:
    inputs:
      mode:
        description: 'Conditonal Execution'
        required: true
        default: 'apply'
        type: choice
        options:
          - apply
          - destroy

env:
  MODE: ${{ github.event.inputs.mode }}

jobs:
  deploy:
    if: env.MODE == 'apply'
    runs-on: ubuntu-latest
    steps:
      - name: Say Apply
        if: ${{ env.MODE == 'apply' }}
        run: echo "MODE == apply"
