name: Conditional Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - condition: true
    if: matrix.condition == true
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run a script
        run: echo "Running the build job because matrix condition is true"
