name: MinIO Deployment

on:
  push:
    branches:
      - mdmn-cluster

env:
  destroy: false

jobs:
  set-condition:
    runs-on: ubuntu-latest
    outputs:
      run-job: ${{ steps.set-output.outputs.RUN_JOB }}
    steps:
      - name: Set condition
        id: set-output
        run: |
          echo "RUN_JOB=${{ env.destroy }}" >> $GITHUB_OUTPUT

  build:
    needs: set-condition
    if: needs.set-condition.outputs.run-job == 'false'
    runs-on: ubuntu-latest
    env:
      AWS_DEFAULT_REGION: "us-west-2"
    steps:
      - name: "check if TF_STATE_FILE DOES NOT exists"
        env: 
            super_secret: ${{ secrets.TF_STATE_FILE }}
        if: ${{ env.super_secret == '' }}
        run: "echo 'TF_STATE_FILE is not set'"
      - name: "check if TF_STATE_FILE exists"
        env: 
            super_secret: ${{ secrets.TF_STATE_FILE }}
        if: ${{ env.super_secret != '' }}
        run: "echo 'TF_STATE_FILE DOES EXIST'"


  destroy:
    needs: set-condition
    if: needs.set-condition.outputs.run-job == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run a script
        run: echo "Running the DESTROY job because condition is met"
