name: MinIO Deployment

on:
  push:
    branches:
      - mdmn-cluster
  workflow_dispatch:
    inputs:
      mode:
        description: 'Conditional Execution'
        required: true
        default: 'apply'
        type: choice
        options:
          - apply
          - destroy

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.mode == 'apply' }}
    steps:
      - name: Say Apply
        run: echo "MODE == apply"
